name: Auto Merge

on:
  pull_request:
    types:
      - closed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Auto merge
        uses: peter-evans/merge-action@v3
        with:
          branch: main
          merge-method: squash
          commit-message: "Auto-merged by GitHub Actions"
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
